### ISSUE TITLE
Plagiarism. 

### ISSUE THREAD

**Issue by AlexisTM** [amirmohajeri/EasyJson#1]
You forgot to change the description of the repo. 

It is still exactly the same as [SimpleJsonPHP](https://github.com/AlexisTM/Simple-Json-PHP).

Plus, you forgot to change the Roadmap:

```markdown
What next ?
The next step is obviously to add routes, which is needed to make a powerful API.
```

vs 

```
What next ?
The next step is obviously to add routes, which is needed to make a powerful API. And then a validation and access restriction system for your API Which are made by EasyJson
```

Why would you ever do this? For credits by violating credits?

Just fork & PR and be a nice contributor.

**Comment by AlexisTM** [comment]
Haha, even the Travis link is still the same :)

**Comment by amirmohajeri** [comment]
Hi @AlexisTM 
No it is't a fork of your repo, When i wrote this code for my personam usage I decided to publish it as a repo in Github. 
I just see your Readme To understand what's going on And It's not like your codes
But I'll change README soon
Excuse me for this! Good luck

**Comment by AlexisTM** [comment]
Actually, the readme is bigger than the code and this is copy pasted. 

Note: You end up in the same situation as I am when I did that library: most of the things are already developed.

For example; the pretty print is one line: 

```php
echo json_encode($json, JSON_PRETTY_PRINT);
```

**Comment by amirmohajeri** [comment]
@AlexisTM 
I changed the README.
Do not forget that this is not an fork of your project!
Best of luck

**Comment by AlexisTM** [comment]
.
